"""
narrative.py
============
Generates a Markdown narrative summary from the aggregated outputs,
suitable for direct inclusion in a paper draft.

Run AFTER aggregate.py has populated output/tables/.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import numpy as np
import pandas as pd

import config

OUT_PATH = os.path.join(config.OUTPUT_DIR, "narrative_summary.md")


def _r(x, d=3):
    if pd.isna(x):
        return "NA"
    return f"{x:.{d}f}"


def _p(x, d=2):
    if pd.isna(x):
        return "NA"
    return f"{x * 100:.{d}f}%"


def _try(path):
    return pd.read_csv(path, index_col=0) if os.path.exists(path) else None


def main():
    print("[narrative] building paper-ready summary...", flush=True)
    T = config.TABLE_DIR

    perf = _try(os.path.join(T, "T01_performance_summary.csv"))
    turn = _try(os.path.join(T, "T02_turnover_summary.csv"))
    conc = _try(os.path.join(T, "T04_concentration_summary.csv"))
    pure_byreg = _try(os.path.join(T, "T05a_pure_portfolio_by_regime.csv"))
    hier_bymac = _try(os.path.join(T, "T05b_hier_portfolio_by_macro_regime.csv"))
    hier_bymkt = _try(os.path.join(T, "T05c_hier_portfolio_by_market_regime.csv"))
    pure_persist = _try(os.path.join(T, "T09a_pure_regime_persistence.csv"))
    hier_macro_persist = _try(os.path.join(T, "T09b_hier_macro_regime_persistence.csv"))
    crisis = None
    cpath = os.path.join(T, "T07_crisis_performance.csv")
    if os.path.exists(cpath):
        crisis = pd.read_csv(cpath, index_col=[0, 1])

    lines = []
    L = lines.append

    L("# Empirical Findings — Auto-Summary\n")
    L("> Generated by `narrative.py`. All numbers reflect the OOS window "
      f"`{config.OOS_START}` → `{config.DATA_END}`.\n")

    if perf is not None:
        L("## 1. Risk-adjusted performance\n")
        L("| Strategy | Sharpe | Sortino | Calmar | Ann Mean | Ann Vol | Max DD (wealth) | Hit Rate |")
        L("|---|---|---|---|---|---|---|---|")
        for s in perf.index:
            r = perf.loc[s]
            L(f"| {s} | {_r(r['Sharpe'])} | {_r(r['Sortino'])} | "
              f"{_r(r.get('Calmar', np.nan))} | {_p(r['Ann Mean'])} | "
              f"{_p(r['Ann Vol'])} | {_p(r['Max DD (wealth)'])} | "
              f"{_p(r['Hit Rate'])} |")
        L("")

        best_sharpe = perf["Sharpe"].idxmax()
        L(f"**Highest Sharpe**: `{best_sharpe}` "
          f"({_r(perf.loc[best_sharpe, 'Sharpe'])}).")
        L("")

        if "Hierarchical_WHMM" in perf.index and "PureMarket_WHMM" in perf.index:
            d_sh = perf.loc["Hierarchical_WHMM", "Sharpe"] - perf.loc["PureMarket_WHMM", "Sharpe"]
            d_dd = perf.loc["Hierarchical_WHMM", "Max DD (wealth)"] - perf.loc["PureMarket_WHMM", "Max DD (wealth)"]
            L(f"**Hierarchical vs Pure-Market**: ΔSharpe = {d_sh:+.3f}, "
              f"ΔMaxDD = {d_dd*100:+.2f} pp.")
            L("")

    if turn is not None:
        L("## 2. Trading frictions and turnover\n")
        L("| Strategy | Mean turnover | 95% q | Days > 1% | Days > 5% |")
        L("|---|---|---|---|---|")
        for s in turn.index:
            r = turn.loc[s]
            L(f"| {s} | {_r(r['Mean'], 4)} | {_r(r['95% Quantile'], 4)} | "
              f"{_p(r['Days > 1%'])} | {_p(r['Days > 5%'])} |")
        L("")

    if conc is not None:
        L("## 3. Diversification (effective # positions)\n")
        L("| Strategy | Mean N_eff | Median N_eff |")
        L("|---|---|---|")
        for s in conc.index:
            r = conc.loc[s]
            L(f"| {s} | {_r(r['Average N_eff'], 2)} | {_r(r['Median N_eff'], 2)} |")
        L("")

    if pure_byreg is not None and not pure_byreg.empty:
        L("## 4. Pure-Market Wasserstein-HMM — performance by market template\n")
        L("| Template | Days | Frac | Sharpe | Ann Mean | Ann Vol | Hit Rate | Max DD (within) |")
        L("|---|---|---|---|---|---|---|---|")
        for r_idx in pure_byreg.index:
            r = pure_byreg.loc[r_idx]
            L(f"| {r_idx} | {int(r['Days'])} | {_p(r['Frac of Sample'])} | "
              f"{_r(r['Sharpe'])} | {_p(r['Ann Mean'])} | {_p(r['Ann Vol'])} | "
              f"{_p(r['Hit Rate'])} | {_p(r['Max DD (within)'])} |")
        L("")

    if hier_bymac is not None and not hier_bymac.empty:
        L("## 5. Hierarchical — performance by MACRO template\n")
        L("| Macro template | Days | Frac | Sharpe | Ann Mean | Ann Vol | Hit Rate | Max DD (within) |")
        L("|---|---|---|---|---|---|---|---|")
        for r_idx in hier_bymac.index:
            r = hier_bymac.loc[r_idx]
            L(f"| {r_idx} | {int(r['Days'])} | {_p(r['Frac of Sample'])} | "
              f"{_r(r['Sharpe'])} | {_p(r['Ann Mean'])} | {_p(r['Ann Vol'])} | "
              f"{_p(r['Hit Rate'])} | {_p(r['Max DD (within)'])} |")
        L("")

    if hier_bymkt is not None and not hier_bymkt.empty:
        L("## 6. Hierarchical — performance by MARKET template\n")
        L("| Market template | Days | Frac | Sharpe | Ann Mean | Ann Vol | Hit Rate | Max DD (within) |")
        L("|---|---|---|---|---|---|---|---|")
        for r_idx in hier_bymkt.index:
            r = hier_bymkt.loc[r_idx]
            L(f"| {r_idx} | {int(r['Days'])} | {_p(r['Frac of Sample'])} | "
              f"{_r(r['Sharpe'])} | {_p(r['Ann Mean'])} | {_p(r['Ann Vol'])} | "
              f"{_p(r['Hit Rate'])} | {_p(r['Max DD (within)'])} |")
        L("")

    if pure_persist is not None:
        L("## 7. Regime persistence (mean spell length, days)\n")
        L("**Pure-market template stability:**\n")
        L("| Template | # spells | Mean length | Median | Max |")
        L("|---|---|---|---|---|")
        for r_idx in pure_persist.index:
            r = pure_persist.loc[r_idx]
            L(f"| {r_idx} | {int(r['n_spells'])} | "
              f"{_r(r['mean_length'], 1)} | {int(r['median_length'])} | "
              f"{int(r['max_length'])} |")
        L("")

    if hier_macro_persist is not None:
        L("**Hierarchical macro template stability:**\n")
        L("| Macro template | # spells | Mean length | Median | Max |")
        L("|---|---|---|---|---|")
        for r_idx in hier_macro_persist.index:
            r = hier_macro_persist.loc[r_idx]
            L(f"| {r_idx} | {int(r['n_spells'])} | "
              f"{_r(r['mean_length'], 1)} | {int(r['median_length'])} | "
              f"{int(r['max_length'])} |")
        L("")

    if crisis is not None:
        L("## 8. Crisis-window stress test\n")
        for c in crisis.index.get_level_values(0).unique():
            L(f"### {c}")
            sub = crisis.loc[c]
            L("| Strategy | Total log return | Sharpe | Max DD |")
            L("|---|---|---|---|")
            for s in sub.index:
                r = sub.loc[s]
                L(f"| {s} | {_p(r['Total log ret'])} | "
                  f"{_r(r['Ann Sharpe'])} | {_p(r['Max DD'])} |")
            L("")

    with open(OUT_PATH, "w") as f:
        f.write("\n".join(lines))
    print(f"[narrative] wrote {OUT_PATH}", flush=True)


if __name__ == "__main__":
    main()
