"""
narrative.py
============
Generates a Markdown narrative summary from the aggregated outputs.
Run AFTER aggregate.py.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import numpy as np
import pandas as pd

import config

OUT_PATH = os.path.join(config.OUTPUT_DIR, "narrative_summary.md")


def _r(x, d=3):
    return "NA" if pd.isna(x) else f"{x:.{d}f}"


def _p(x, d=2):
    return "NA" if pd.isna(x) else f"{x * 100:.{d}f}%"


def _try(path):
    return pd.read_csv(path, index_col=0) if os.path.exists(path) else None


def main():
    print("[narrative] building paper-ready summary...", flush=True)
    T = config.TABLE_DIR

    perf = _try(os.path.join(T, "T01_performance_summary.csv"))
    turn = _try(os.path.join(T, "T02_turnover_summary.csv"))
    conc = _try(os.path.join(T, "T04_concentration_summary.csv"))
    pure_byreg = _try(os.path.join(T, "T05a_pure_by_regime.csv"))
    hierB_bymac = _try(os.path.join(T, "T05b_hierB_by_macro_regime.csv"))
    hierC_bymac = _try(os.path.join(T, "T05c_hierC_by_macro_regime.csv"))
    persist_pure = _try(os.path.join(T, "T09a_pure_persistence.csv"))
    persist_B = _try(os.path.join(T, "T09b_hierB_macro_persistence.csv"))
    persist_C = _try(os.path.join(T, "T09c_hierC_macro_persistence.csv"))
    stressC = _try(os.path.join(T, "T10_hierC_stress_summary.csv"))
    crisis = None
    cpath = os.path.join(T, "T07_crisis_performance.csv")
    if os.path.exists(cpath):
        crisis = pd.read_csv(cpath, index_col=[0, 1])

    L = []

    L.append("# Empirical Findings — Auto-Summary\n")
    L.append("> Generated by `narrative.py`. OOS window "
             f"`{config.OOS_START}` → `{config.DATA_END}`.\n")
    L.append("Three regime-aware strategies are compared against two "
             "passive benchmarks:\n")
    L.append("- **PureMarket_WHMM** — Boukardagha (2026) replication.")
    L.append("- **Hierarchical_B** — macro × market joint-mixture moments, no tilt.")
    L.append("- **Hierarchical_C** — macro layer as a *risk modulator* "
             "(asset-outcome-space templates, tempered posterior, "
             "stress-scaled risk aversion); market layer owns direction.\n")

    if perf is not None:
        L.append("## 1. Risk-adjusted performance\n")
        L.append("| Strategy | Sharpe | Sortino | Calmar | Ann Mean | Ann Vol | Max DD (wealth) | Hit Rate |")
        L.append("|---|---|---|---|---|---|---|---|")
        for s in perf.index:
            r = perf.loc[s]
            L.append(f"| {s} | {_r(r['Sharpe'])} | {_r(r['Sortino'])} | "
                     f"{_r(r.get('Calmar', np.nan))} | {_p(r['Ann Mean'])} | "
                     f"{_p(r['Ann Vol'])} | {_p(r['Max DD (wealth)'])} | "
                     f"{_p(r['Hit Rate'])} |")
        L.append("")
        best = perf["Sharpe"].idxmax()
        L.append(f"**Highest Sharpe**: `{best}` ({_r(perf.loc[best,'Sharpe'])}).")
        best_dd = perf["Max DD (wealth)"].idxmax()  # closest to 0
        L.append(f"**Smallest max drawdown**: `{best_dd}` "
                 f"({_p(perf.loc[best_dd,'Max DD (wealth)'])}).")
        L.append("")
        ref = "PureMarket_WHMM"
        for s in ("Hierarchical_B", "Hierarchical_C"):
            if s in perf.index and ref in perf.index:
                dsh = perf.loc[s,"Sharpe"] - perf.loc[ref,"Sharpe"]
                ddd = perf.loc[s,"Max DD (wealth)"] - perf.loc[ref,"Max DD (wealth)"]
                L.append(f"**{s} vs {ref}**: ΔSharpe = {dsh:+.3f}, "
                         f"ΔMaxDD = {ddd*100:+.2f} pp.")
        L.append("")

    if turn is not None:
        L.append("## 2. Trading frictions and turnover\n")
        L.append("| Strategy | Mean turnover | 95% q | Days > 1% | Days > 5% |")
        L.append("|---|---|---|---|---|")
        for s in turn.index:
            r = turn.loc[s]
            L.append(f"| {s} | {_r(r['Mean'],4)} | {_r(r['95% Quantile'],4)} | "
                     f"{_p(r['Days > 1%'])} | {_p(r['Days > 5%'])} |")
        L.append("")

    if conc is not None:
        L.append("## 3. Diversification (effective # positions)\n")
        L.append("| Strategy | Mean N_eff | Median N_eff |")
        L.append("|---|---|---|")
        for s in conc.index:
            r = conc.loc[s]
            L.append(f"| {s} | {_r(r['Average N_eff'],2)} | {_r(r['Median N_eff'],2)} |")
        L.append("")

    def regime_block(title, tab):
        if tab is None or tab.empty:
            return
        L.append(f"## {title}\n")
        L.append("| Regime | Days | Frac | Sharpe | Ann Mean | Ann Vol | Hit Rate | Max DD (within) |")
        L.append("|---|---|---|---|---|---|---|---|")
        for idx in tab.index:
            r = tab.loc[idx]
            L.append(f"| {idx} | {int(r['Days'])} | {_p(r['Frac of Sample'])} | "
                     f"{_r(r['Sharpe'])} | {_p(r['Ann Mean'])} | {_p(r['Ann Vol'])} | "
                     f"{_p(r['Hit Rate'])} | {_p(r['Max DD (within)'])} |")
        L.append("")

    regime_block("4. Pure-Market — performance by market template", pure_byreg)
    regime_block("5. Hierarchical B — performance by MACRO template", hierB_bymac)
    regime_block("6. Hierarchical C — performance by MACRO template", hierC_bymac)

    # Macro persistence comparison
    if persist_B is not None or persist_C is not None:
        L.append("## 7. Macro regime persistence (mean spell length, days)\n")
        for label, pt in [("Hierarchical B (feature-space templates)", persist_B),
                          ("Hierarchical C (outcome-space templates)", persist_C)]:
            if pt is None:
                continue
            L.append(f"**{label}:**\n")
            L.append("| Macro template | # spells | Mean length | Median | Max |")
            L.append("|---|---|---|---|---|")
            for idx in pt.index:
                r = pt.loc[idx]
                L.append(f"| {idx} | {int(r['n_spells'])} | {_r(r['mean_length'],1)} | "
                         f"{int(r['median_length'])} | {int(r['max_length'])} |")
            L.append("")

    if stressC is not None:
        L.append("## 8. Hierarchical C — macro stress & effective risk aversion\n")
        L.append("| Statistic | macro_stress | gamma_eff |")
        L.append("|---|---|---|")
        for idx in stressC.index:
            r = stressC.loc[idx]
            L.append(f"| {idx} | {_r(r['macro_stress'],3)} | {_r(r['gamma_eff'],3)} |")
        L.append("")
        L.append(f"(Base risk aversion gamma = {config.LAM}; "
                 f"gamma_eff = gamma · (1 + {config.HIER_C_KAPPA_GAMMA} · stress).)")
        L.append("")

    if crisis is not None:
        L.append("## 9. Crisis-window stress test\n")
        for c in crisis.index.get_level_values(0).unique():
            L.append(f"### {c}")
            sub = crisis.loc[c]
            L.append("| Strategy | Total log return | Sharpe | Max DD |")
            L.append("|---|---|---|---|")
            for s in sub.index:
                r = sub.loc[s]
                L.append(f"| {s} | {_p(r['Total log ret'])} | "
                         f"{_r(r['Ann Sharpe'])} | {_p(r['Max DD'])} |")
            L.append("")

    with open(OUT_PATH, "w") as f:
        f.write("\n".join(L))
    print(f"[narrative] wrote {OUT_PATH}", flush=True)


if __name__ == "__main__":
    main()
